[workspace]
members = [
    "crates/agent_core",
    "crates/brain_core",
    "crates/chm",
    "crates/core_types",
    "crates/dhm",
    "crates/evaluator",
    "crates/field_engine",
    "crates/hybrid_vm",
    "crates/profile",
    "crates/memory_store",
    "crates/shm",
    "crates/memory_space",
    "crates/num-complex",
    "crates/runtime_vm",
    "crates/interface_ui",
    "apps/cli",
    "apps/desktop",
    "apps/server",
    "apps/lsp"
]
resolver = "2"

[workspace.dependencies]
agent_core = { path = "crates/agent_core" }
brain_core = { path = "crates/brain_core" }
chm = { path = "crates/chm" }
core_types = { path = "crates/core_types" }
dhm = { path = "crates/dhm" }
evaluator = { path = "crates/evaluator" }
field_engine = { path = "crates/field_engine" }
hybrid_vm = { path = "crates/hybrid_vm" }
interface_ui = { path = "crates/interface_ui" }
memory_store = { path = "crates/memory_store" }
memory_space = { path = "crates/memory_space" }
num-complex = { path = "crates/num-complex" }
profile = { path = "crates/profile" }
runtime_vm = { path = "crates/runtime_vm" }
shm = { path = "crates/shm" }
