[workspace]
members = [
    "crates/agent_core",
    "crates/brain_core",
    "crates/chm",
    "crates/core_types",
    "crates/dhm",
    "crates/field_engine",
    "crates/hybrid_vm",
    "crates/profile",
    "crates/memory_store",
    "crates/shm",
    "crates/memory_space",
    "crates/num-complex",
    "crates/runtime_vm",
    "crates/interface_ui",
    "crates/language_dhm",
    "crates/meaning_extractor",
    "crates/semantic_dhm",
    "crates/recomposer",
    "crates/design_reasoning",
    "apps/cli",
    "apps/gui",
    "apps/desktop",
    "apps/server",
    "apps/lsp"
]
resolver = "2"

[workspace.dependencies]
agent_core = { path = "crates/agent_core" }
brain_core = { path = "crates/brain_core" }
chm = { path = "crates/chm" }
core_types = { path = "crates/core_types" }
dhm = { path = "crates/dhm" }
field_engine = { path = "crates/field_engine" }
hybrid_vm = { path = "crates/hybrid_vm" }
interface_ui = { path = "crates/interface_ui" }
memory_store = { path = "crates/memory_store" }
memory_space = { path = "crates/memory_space" }
language_dhm = { path = "crates/language_dhm" }
meaning_extractor = { path = "crates/meaning_extractor" }
semantic_dhm = { path = "crates/semantic_dhm" }
recomposer = { path = "crates/recomposer" }
design_reasoning = { path = "crates/design_reasoning" }
num-complex = { path = "crates/num-complex" }
profile = { path = "crates/profile" }
runtime_vm = { path = "crates/runtime_vm" }
shm = { path = "crates/shm" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
